_extends: .github

repository:
  name: bjd2385.github.io
  description: My observation [b]log
  homepage: https://blog.aperiodicity.com

  # A comma-separated list of topics to set on the repository
  topics: astronomy, observational astronomy, log
  private: false
