title: Observation [b]log
email: bjd2385.linux@gmail.com
description: >-
  My astronomy observation [b]log
baseurl: ""
url: "https://blog.aperiodicity.com"
twitter_username: bjd2385
github_username:  bjd2385

# Build settings
theme: minima
plugins:
  - jekyll-feed
