title: Observation [b]log
email: bjd2385.linux@gmail.com
author: Emma Doyle
description: >-
  A place where I post my random observations of the night sky
baseurl: ""
url: https://blog.aperiodicity.com
twitter_username: bjd2385
github_username:  bjd2385
linkedin_username: bjd2385
paginate: 10
paginate_path: /posts/page:num/
google_analytics: G-2PVB8KPX2Z

# Build settings
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-last-modified-at
# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
# https://github.com/gjtorikian/jekyll-last-modified-at
last-modified-at:
    date-format: '%d-%b-%y'
