title: Observation [b]log
email: bjd2385.linux@gmail.com
description: >-
  My astronomy observation [b]log
baseurl: ""
url: https://blog.aperiodicity.com
twitter_username: bjd2385
github_username:  bjd2385

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-last-modified-at
# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
# https://github.com/gjtorikian/jekyll-last-modified-at
last-modified-at:
    date-format: '%d-%b-%y'
