version: 2.1

setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.8.2


workflows:
  bjd2385.github.io:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          modules: |
            /scripts
